name: Marp Slide Generator

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Marp Build
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: slides.md -o index.html --theme academic.css
        env:
          MARP_USER: root:root

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # You can specify a different directory if needed
